// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiqqmnwZiaKRpHK6ORndB8JzjCJnEV5fc',
    appId: '1:313828643331:web:f6cf0041e3f25183603436',
    messagingSenderId: '313828643331',
    projectId: 'app-acordeoneros',
    authDomain: 'app-acordeoneros.firebaseapp.com',
    storageBucket: 'app-acordeoneros.firebasestorage.app',
    measurementId: 'G-CEBTHYZMDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpvExf4Bw6Eug17ds20tgVY7vYGgQTmtg',
    appId: '1:313828643331:android:77bdadd85a97bda6603436',
    messagingSenderId: '313828643331',
    projectId: 'app-acordeoneros',
    storageBucket: 'app-acordeoneros.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACJwLgF_F0404vLey97N5VmOeXF6u2xz0',
    appId: '1:313828643331:ios:29c0b602a487d95a603436',
    messagingSenderId: '313828643331',
    projectId: 'app-acordeoneros',
    storageBucket: 'app-acordeoneros.firebasestorage.app',
    iosBundleId: 'com.example.comunidadAcordeoneros',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACJwLgF_F0404vLey97N5VmOeXF6u2xz0',
    appId: '1:313828643331:ios:29c0b602a487d95a603436',
    messagingSenderId: '313828643331',
    projectId: 'app-acordeoneros',
    storageBucket: 'app-acordeoneros.firebasestorage.app',
    iosBundleId: 'com.example.comunidadAcordeoneros',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiqqmnwZiaKRpHK6ORndB8JzjCJnEV5fc',
    appId: '1:313828643331:web:7ab0e9bba5c1b81d603436',
    messagingSenderId: '313828643331',
    projectId: 'app-acordeoneros',
    authDomain: 'app-acordeoneros.firebaseapp.com',
    storageBucket: 'app-acordeoneros.firebasestorage.app',
    measurementId: 'G-STZVCP3Y3F',
  );
}
